version: "3.8"

services:
    db:
        image: postgres
        container_name: youtube_transcript_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "54322:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
